name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: "Thank you for creating an issue, if you are looking to submit for the competition please use the pull requests"
        pr-message: "Thanks for making a pull request, please make sure that you are submitting your entry to the correct folder"
